//! Queued work: timers and animation frames.
//!
//! Nothing runs on its own. Work piles up until the lifecycle drains it, which
//! is what makes a load reproducible.
//!
//! But time does pass. A timer is due at a moment, not merely after the ones
//! ahead of it, and running one early is not a harmless approximation: the
//! pattern every page uses to give a request a deadline is
//!
//! ```js
//! const timer = setTimeout(() => controller.abort(), 35000);
//! const response = await fetch(url, { signal: controller.signal });
//! ```
//!
//! and a queue with no clock fires that abort immediately — cancelling a
//! request that had already succeeded, and leaving the page to report a
//! failure that never happened. That is exactly what hcker.news did here: the
//! stories arrived, 26KB of them, and were thrown away by their own timeout.

use std::cell::{Cell, RefCell};

use rquickjs::{
    Coerced, Ctx, Function, Object, Value,
    function::{Opt, Rest},
};

use super::Sharing;

/// One piece of queued work, and what to call it with.
struct Task {
    handle: u64,
    /// When this may run, as milliseconds on the same clock `now` reads.
    due: f64,
    callback: rquickjs::Persistent<Function<'static>>,
    args: Vec<rquickjs::Persistent<Value<'static>>>,
}

/// Everything scheduled and not yet run.
#[derive(Default)]
pub struct Queue {
    timers: RefCell<Vec<Task>>,
    frames: RefCell<Vec<Task>>,
    next: Cell<u64>,
}

impl Queue {
    /// Drops every retained callback. Must run while the context is alive.
    pub fn release(&self) {
        self.timers.borrow_mut().clear();
        self.frames.borrow_mut().clear();
    }

    fn handle(&self) -> u64 {
        let next = self.next.get() + 1;
        self.next.set(next);
        next
    }
}

fn schedule<'js>(
    ctx: &Ctx<'js>,
    frame: bool,
    callback: Function<'js>,
    delay: f64,
    args: Vec<Value<'js>>,
) -> rquickjs::Result<u64> {
    let shared = ctx
        .userdata::<Sharing>()
        .ok_or_else(|| rquickjs::Error::new_from_js("Realm", "a document to belong to"))?;
    let handle = shared.tasks.handle();
    let task = Task {
        handle,
        due: now() + delay.max(0.0),
        callback: rquickjs::Persistent::save(ctx, callback),
        args: args
            .into_iter()
            .map(|arg| rquickjs::Persistent::save(ctx, arg))
            .collect(),
    };
    if frame {
        shared.tasks.frames.borrow_mut().push(task);
    } else {
        shared.tasks.timers.borrow_mut().push(task);
    }
    Ok(handle)
}

/// Runs one task, reporting rather than propagating what it throws — a page's
/// broken callback is the page's problem, not the load's.
fn run(ctx: &Ctx<'_>, task: Task, frame_time: Option<f64>) -> rquickjs::Result<()> {
    let callback = task.callback.restore(ctx)?;
    let outcome = match frame_time {
        Some(time) => callback.call::<_, Value>((time,)),
        None => {
            let args = rquickjs::function::Args::new(ctx.clone(), task.args.len());
            let mut args = args;
            for arg in task.args {
                args.push_arg(arg.restore(ctx)?)?;
            }
            callback.call_arg::<Value>(args)
        }
    };
    // What was thrown, not that something was: an `rquickjs::Error` for a JS
    // exception prints "Exception generated by QuickJS" and leaves the thrown
    // value in the context. A timer that failed silently for want of that line
    // is a bad afternoon.
    if let Err(error) = outcome
        && let Ok(console) = ctx.globals().get::<_, Object>("__console")
        && let Ok(report) = console.get::<_, Function>("error")
    {
        let detail = crate::realm::convert::exception_text(ctx, error);
        let _ = report.call::<_, Value>((format!("task threw: {detail}"),));
    }
    Ok(())
}

/// Drains one round of queued work. Answers whether there was any.
pub(crate) fn drain(ctx: &Ctx<'_>) -> rquickjs::Result<bool> {
    let (mut timers, frames) = {
        let shared = ctx
            .userdata::<Sharing>()
            .ok_or_else(|| rquickjs::Error::new_from_js("Realm", "a document to belong to"))?;
        let timers = shared.tasks.timers.take();
        let frames = shared.tasks.frames.take();
        (timers, frames)
    };
    if timers.is_empty() && frames.is_empty() {
        return Ok(false);
    }

    // Due first, then by the order they were scheduled, which is what decides
    // between two timers due at the same moment.
    timers.sort_by(|a, b| {
        a.due
            .total_cmp(&b.due)
            .then_with(|| a.handle.cmp(&b.handle))
    });

    // Only what is actually due. A timer set for later goes back on the queue:
    // it may come due while the rest of this round runs, and if it never does,
    // it never runs — which is the whole point. See this module's own note.
    let moment = now();
    let (due, waiting): (Vec<Task>, Vec<Task>) =
        timers.into_iter().partition(|it| it.due <= moment);
    let ran = !due.is_empty() || !frames.is_empty();
    if !waiting.is_empty() {
        let shared = ctx
            .userdata::<Sharing>()
            .ok_or_else(|| rquickjs::Error::new_from_js("Realm", "a document to belong to"))?;
        shared.tasks.timers.borrow_mut().extend(waiting);
    }

    for timer in due {
        run(ctx, timer, None)?;
    }
    // An animation frame is always for the next frame, and this is it.
    for frame in frames {
        run(ctx, frame, Some(0.0))?;
    }
    Ok(ran)
}

/// Milliseconds on a clock that only goes forwards.
///
/// The same clock a timer's deadline is measured against, and nothing else
/// depends on where it starts — only on the difference between two readings.
fn now() -> f64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|since| since.as_secs_f64() * 1000.0)
        .unwrap_or(0.0)
}

/// How long until the earliest timer that has not come due, in milliseconds,
/// or nothing when there is none.
///
/// What the difference between an empty queue and a waiting one costs: a page
/// that schedules its render for fifty milliseconds' time has queued work, and
/// a drain that stops because nothing is due *this instant* throws it away. The
/// page then never renders, and says nothing about why.
impl Queue {
    pub(crate) fn waiting_for(&self) -> Option<f64> {
        let soonest = self
            .timers
            .borrow()
            .iter()
            .map(|it| it.due)
            .fold(f64::INFINITY, f64::min);
        soonest.is_finite().then(|| (soonest - now()).max(0.0))
    }
}

pub(super) fn install<'js>(ctx: &Ctx<'js>, api: &Object<'js>) -> rquickjs::Result<()> {
    let globals = ctx.globals();

    globals.set("setTimeout", Function::new(ctx.clone(), set_timeout)?)?;
    globals.set("clearTimeout", Function::new(ctx.clone(), clear_timeout)?)?;
    globals.set(
        "requestAnimationFrame",
        Function::new(ctx.clone(), request_frame)?,
    )?;
    api.set("drainTasks", Function::new(ctx.clone(), drain_binding)?)?;
    Ok(())
}

fn set_timeout<'js>(
    ctx: Ctx<'js>,
    callback: Function<'js>,
    delay: Opt<Coerced<f64>>,
    args: Rest<Value<'js>>,
) -> rquickjs::Result<u64> {
    let delay = delay.0.map(|delay| delay.0).unwrap_or(0.0);
    schedule(
        &ctx,
        false,
        callback,
        if delay.is_nan() { 0.0 } else { delay },
        args.0,
    )
}

/// Cancels a timer. Frames are not searched, matching what the Prelude did:
/// `cancelAnimationFrame` was an alias for this.
///
/// Anything that is not a number it knows is ignored rather than refused —
/// `null`, `undefined`, a string, a handle already fired. HTML says an id that
/// does not match a timer is simply not cancelled, and code relies on it:
/// testharness.js opens by clearing a timeout it has not set yet, so a throw
/// here stopped every test in the suite before it had begun.
fn clear_timeout<'js>(ctx: Ctx<'js>, handle: Opt<Value<'js>>) -> rquickjs::Result<()> {
    let Some(handle) = handle
        .0
        .as_ref()
        .and_then(Value::as_number)
        .filter(|it| it.is_finite() && *it >= 0.0)
        .map(|it| it as u64)
    else {
        return Ok(());
    };
    let shared = ctx
        .userdata::<Sharing>()
        .ok_or_else(|| rquickjs::Error::new_from_js("Realm", "a document to belong to"))?;
    shared
        .tasks
        .timers
        .borrow_mut()
        .retain(|timer| timer.handle != handle);
    Ok(())
}

fn request_frame<'js>(ctx: Ctx<'js>, callback: Function<'js>) -> rquickjs::Result<u64> {
    schedule(&ctx, true, callback, 0.0, Vec::new())
}

fn drain_binding(ctx: Ctx<'_>) -> rquickjs::Result<bool> {
    drain(&ctx)
}
