[package]
name = "toy-browser-engine"
description = "The smallest set of operations a browser automation API can be built on."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
toy-browser-fetch.workspace = true
serde_json.workspace = true
blitz-dom = { version = "0.3.0-beta.2", features = ["floats"] }
blitz-html = "0.3.0-beta.2"
rquickjs = { version = "0.12.2", features = ["macro", "classes", "properties", "loader"] }
xml5ever = "0.39"
html5ever = "0.39"

[lints]
workspace = true
