[package]
name = "toy-browser-engine"
description = "The smallest set of operations a browser automation API can be built on."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
toy-browser-fetch.workspace = true
serde_json.workspace = true
blitz-dom = { path = "../../vendor/blitz-dom", default-features = false, features = [
    "floats",
    "svg",
    "woff",
    "system-fonts",
    "file-input",
] }
blitz-html = { path = "../../vendor/blitz-html" }
rquickjs = { version = "0.12.2", features = ["macro", "classes", "properties", "loader"] }
xml5ever = "0.39"
html5ever = "0.39"

[lints]
workspace = true
